services:
  - type: web
    name: cash-linkify
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://cash-linkify.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_DRIVER
        value: sync
      - key: LOG_CHANNEL
        value: stack
    disk:
      name: cash-linkify-disk
      mountPath: /opt/render/project/src/storage
      sizeGB: 1
